server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: booking_event
  datasource:
    url: "jdbc:mysql://localhost:3306/event_booking"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY:AIzaSy_DAP_KEY_GEMINI_CUA_BAN_VAO_DAY}
        chat:
          options:
            model: gemini-1.5-flash # Model tốc độ cao, hoàn toàn miễn phí
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method 
