server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: booking_event
  datasource:
    url: "jdbc:mysql://localhost:3306/event_booking"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ai:
    prompt:
      search-events: ${AI_PROMPT_SEARCH_EVENT_PATH:classpath:prompts/search-events.st}
      ask-events: ${AI_PROMPT_ASK_EVENT_PATH:classpath:prompts/ask-event.st}
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: ${GEMINI_BASE_URL:https://generativelanguage.googleapis.com/v1beta/openai/}
      chat:
        options:
          model: ${GEMINI_MODEL:gemini-1.5-flash}
          temperature: 0.2
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  signerKey: "${JWT_SIGNER_KEY:9j8FvKmXz1WbQ2dE5hT6Y7uI8oKpL0mN1aBsCdEfGhI=abcdefghijklmnopqrstuvwxyz123456}"
  #Thiết lập thời gian của JWT tùy thuộc vào hệ thống
  valid-duration: 3600 # in second
  refreshable-duration: 36000 #in second

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method