server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: booking_event
  datasource:
    url: "jdbc:mysql://localhost:3306/event_booking"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ai:
    anthropic:
      api-key: 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
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method 